# Generated by Django 4.2.3 on 2023-07-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moving_status', models.CharField(choices=[('0', 'Not Moving'), ('1', 'Moving Upward'), ('2', 'Moving Downward')], default='0', max_length=1)),
                ('is_door_open', models.BooleanField(default=False)),
                ('is_operational', models.BooleanField(default=True)),
                ('current_floor', models.IntegerField(default=0)),
                ('target_floor', models.IntegerField(default=0)),
            ],
        ),
    ]