# Generated by Django 4.2.3 on 2023-07-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='elevator',
            table='elevators',
        ),
    ]
