# Generated by Django 4.2.3 on 2023-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_controls', '0002_alter_elevator_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='service_request',
            field=models.JSONField(default=list),
        ),
    ]
