# Generated by Django 4.2.3 on 2023-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_controls', '0003_elevator_service_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='moving_status',
            field=models.IntegerField(choices=[('0', 'Not Moving'), ('1', 'Moving Upward'), ('-1', 'Moving Downward')], default='0'),
        ),
    ]
